'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Athlete
    Public Property AthleteID As Integer
    Public Property AthleteName As String
    Public Property AthleteSurname As String
    Public Property AthleteAddress As String
    Public Property AthleteCountry As String
    Public Property ClubName As String
    Public Property Genre As String
    Public Property YOB As String
    Public Property CreateDateTime As Date
    Public Property StartNumber As String
    Public Property CategoryName As String
    Public Property lp As Nullable(Of Long)

End Class
