'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class DbConnectionWebio
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DbConnectionWebio")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Function ResultsRead(eventID As Nullable(Of Integer)) As ObjectResult(Of Results)
        Dim eventIDParameter As ObjectParameter = If(eventID.HasValue, New ObjectParameter("EventID", eventID), New ObjectParameter("EventID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Results)("ResultsRead", eventIDParameter)
    End Function

    Public Overridable Function AthleteRead(eventID As Nullable(Of Integer)) As ObjectResult(Of Athlete)
        Dim eventIDParameter As ObjectParameter = If(eventID.HasValue, New ObjectParameter("EventID", eventID), New ObjectParameter("EventID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of Athlete)("AthleteRead", eventIDParameter)
    End Function

End Class
